unit cnsexcel;

interface

const
{XlPageOrientation}
 xlLandscape = 2;
 xlPortrait = 1;
{XlPaperSize}
 xlPaper10x14 = 16;
 xlPaper11x17 = 17;
 xlPaperA3 = 8;
 xlPaperA4 = 9;
 xlPaperA4Small = 10;
 xlPaperA5 = 11;
 xlPaperB4 = 12;
 xlPaperB5 = 13;
 xlPaperCsheet = 24;
 xlPaperDsheet = 25;
 xlPaperEnvelope10 = 20;
 xlPaperEnvelope11 = 21;
 xlPaperEnvelope12 = 22;
 xlPaperEnvelope14 = 23;
 xlPaperEnvelope9 = 19;
 xlPaperEnvelopeB4 = 33;
 xlPaperEnvelopeB5 = 34;
 xlPaperEnvelopeB6 = 35;
 xlPaperEnvelopeC3 = 29;
 xlPaperEnvelopeC4 = 30;
 xlPaperEnvelopeC5 = 28;
 xlPaperEnvelopeC6 = 31;
 xlPaperEnvelopeC65 = 32;
 xlPaperEnvelopeDL = 27;
 xlPaperEnvelopeItaly = 36;
 xlPaperEnvelopeMonarch = 37;
 xlPaperEnvelopePersonal = 38;
 xlPaperEsheet = 26;
 xlPaperExecutive = 7;
 xlPaperFanfoldLegalGerman = 41;
 xlPaperFanfoldStdGerman = 40;
 xlPaperFanfoldUS = 39;
 xlPaperFolio = 14;
 xlPaperLedger = 4;
 xlPaperLegal = 5;
 xlPaperLetter = 1;
 xlPaperLetterSmall = 2;
 xlPaperNote = 18;
 xlPaperQuarto = 15;
 xlPaperStatement = 6;
 xlPaperTabloid = 3;
 xlPaperUser = 256;
{XlPasteSpecialOperation}
 xlPasteSpecialOperationAdd = 2;
 xlPasteSpecialOperationDivide = 5;
 xlPasteSpecialOperationMultiply = 4;
 xlPasteSpecialOperationNone = -4142;
 xlPasteSpecialOperationSubtract = 3;
{XlPasteType}
 xlPasteAll = -4104;
 xlPasteAllExceptBorders = 6;
 xlPasteFormats = -4122;
 xlPasteFormulas = -4123;
 xlPasteComments = -4144;
 xlPasteValues = -4163;
{XlClipboardFormat}
 xlClipboardFormatBIFF = 8;
 xlClipboardFormatBIFF2 = 18;
 xlClipboardFormatBIFF3 = 20;
 xlClipboardFormatBIFF4 = 30;
 xlClipboardFormatBinary = 15;
 xlClipboardFormatBitmap = 9;
 xlClipboardFormatCGM = 13;
 xlClipboardFormatCSV = 5;
 xlClipboardFormatDIF = 4;
 xlClipboardFormatDspText = 12;
 xlClipboardFormatEmbeddedObject = 21;
 xlClipboardFormatEmbedSource = 22;
 xlClipboardFormatLink = 11;
 xlClipboardFormatLinkSource = 23;
 xlClipboardFormatLinkSourceDesc = 32;
 xlClipboardFormatMovie = 24;
 xlClipboardFormatNative = 14;
 xlClipboardFormatObjectDesc = 31;
 xlClipboardFormatObjectLink = 19;
 xlClipboardFormatOwnerLink = 17;
 xlClipboardFormatPICT = 2;
 xlClipboardFormatPrintPICT = 3;
 xlClipboardFormatRTF = 7;
 xlClipboardFormatScreenPICT = 29;
 xlClipboardFormatStandardFont = 28;
 xlClipboardFormatStandardScale = 27;
 xlClipboardFormatSYLK = 6;
 xlClipboardFormatTable = 16;
 xlClipboardFormatText = 0;
 xlClipboardFormatToolFace = 25;
 xlClipboardFormatToolFacePICT = 26;
 xlClipboardFormatVALU = 1;
 xlClipboardFormatWK1 = 10;

 xlAll = -4104;
 xlAutomatic = -4105;
 xlBoth = 1;
 xlCenter = -4108;
 xlChecker = 9;
 xlCircle = 8;
 xlCorner = 2;
 xlCrissCross = 16;
 xlCross = 4;
 xlDiamond = 2;
 xlDistributed = -4117;
 xlDoubleAccounting = 5;
 xlFixedValue = 1;
 xlFormats = -4122;
 xlGray16 = 17;
 xlGray8 = 18;
 xlGrid = 15;
 xlHigh = -4127;
 xlInside = 2;
 xlJustify = -4130;
 xlLightDown = 13;
 xlLightHorizontal = 11;
 xlLightUp = 14;
 xlLightVertical = 12;
 xlLow = -4134;
 xlManual = -4135;
 xlMinusValues = 3;
 xlModule = -4141;
 xlNextToAxis = 4;
 xlNone = -4142;
 xlNotes = -4144;
 xlOff = -4146;
 xlOn = 1;
 xlPercent = 2;
 xlPlus = 9;
 xlPlusValues = 2;
 xlSemiGray75 = 10;
 xlShowLabel = 4;
 xlShowLabelAndPercent = 5;
 xlShowPercent = 3;
 xlShowValue = 2;
 xlSimple = -4154;
 xlSingle = 2;
 xlSingleAccounting = 4;
 xlSolid = 1;
 xlSquare = 1;
 xlStar = 5;
 xlStError = 4;
 xlToolbarButton = 2;
 xlTriangle = 3;
 xlGray25 = -4124;
 xlGray50 = -4125;
 xlGray75 = -4126;
 xlBottom = -4107;
 xlLeft = -4131;
 xlRight = -4152;
 xlTop = -4160;
 xl3DBar = -4099;
 xl3DSurface = -4103;
 xlBar = 2;
 xlColumn = 3;
 xlCombination = -4111;
 xlCustom = -4114;
 xlDefaultAutoFormat = -1;
 xlMaximum = 2;
 xlMinimum = 4;
 xlOpaque = 3;
 xlTransparent = 2;
 xlBidi = -5000;
 xlLatin = -5001;
 xlContext = -5002;
 xlLTR = -5003;
 xlRTL = -5004;
 xlVisualCursor = 2;
 xlLogicalCursor = 1;
 xlSystem = 1;
 xlPartial = 3;
 xlHindiNumerals = 3;
 xlBidiCalendar = 3;
 xlGregorian = 2;
 xlComplete = 4;
 xlScale = 3;
 xlClosed = 3;
 xlColor1 = 7;
 xlColor2 = 8;
 xlColor3 = 9;
 xlConstants = 2;
 xlContents = 2;
 xlBelow = 1;
 xlCascade = 7;
 xlCenterAcrossSelection = 7;
 xlChart4 = 2;
 xlChartSeries = 17;
 xlChartShort = 6;
 xlChartTitles = 18;
 xlClassic1 = 1;
 xlClassic2 = 2;
 xlClassic3 = 3;
 xl3DEffects1 = 13;
 xl3DEffects2 = 14;
 xlAbove = 0;
 xlAccounting1 = 4;
 xlAccounting2 = 5;
 xlAccounting3 = 6;
 xlAccounting4 = 17;
 xlAdd = 2;
 xlDebugCodePane = 13;
 xlDesktop = 9;
 xlDirect = 1;
 xlDivide = 5;
 xlDoubleClosed = 5;
 xlDoubleOpen = 4;
 xlDoubleQuote = 1;
 xlEntireChart = 20;
 xlExcelMenus = 1;
 xlExtended = 3;
 xlFill = 5;
 xlFirst = 0;
 xlFloating = 5;
 xlFormula = 5;
 xlGeneral = 1;
 xlGridline = 22;
 xlIcons = 1;
 xlImmediatePane = 12;
 xlInteger = 2;
 xlLast = 1;
 xlLastCell = 11;
 xlList1 = 10;
 xlList2 = 11;
 xlList3 = 12;
 xlLocalFormat1 = 15;
 xlLocalFormat2 = 16;
 xlLong = 3;
 xlLotusHelp = 2;
 xlMacrosheetCell = 7;
 xlMixed = 2;
 xlMultiply = 4;
 xlNarrow = 1;
 xlNoDocuments = 3;
 xlOpen = 2;
 xlOutside = 3;
 xlReference = 4;
 xlSemiautomatic = 2;
 xlShort = 1;
 xlSingleQuote = 2;
 xlStrict = 2;
 xlSubtract = 3;
 xlTextBox = 16;
 xlTiled = 1;
 xlTitleBar = 8;
 xlToolbar = 1;
 xlVisible = 12;
 xlWatchPane = 11;
 xlWide = 3;
 xlWorkbookTab = 6;
 xlWorksheet4 = 1;
 xlWorksheetCell = 3;
 xlWorksheetShort = 5;
 xlAllExceptBorders = 6;
 xlLeftToRight = 2;
 xlTopToBottom = 1;
 xlVeryHidden = 2;
 xlDrawingObject = 14;
{XlChartType}
 xlColumnClustered = 51;
 xlColumnStacked = 52;
 xlColumnStacked100 = 53;
 xl3DColumnClustered = 54;
 xl3DColumnStacked = 55;
 xl3DColumnStacked100 = 56;
 xlBarClustered = 57;
 xlBarStacked = 58;
 xlBarStacked100 = 59;
 xl3DBarClustered = 60;
 xl3DBarStacked = 61;
 xl3DBarStacked100 = 62;
 xlLineStacked = 63;
 xlLineStacked100 = 64;
 xlLineMarkers = 65;
 xlLineMarkersStacked = 66;
 xlLineMarkersStacked100 = 67;
 xlPieOfPie = 68;
 xlPieExploded = 69;
 xl3DPieExploded = 70;
 xlBarOfPie = 71;
 xlXYScatterSmooth = 72;
 xlXYScatterSmoothNoMarkers = 73;
 xlXYScatterLines = 74;
 xlXYScatterLinesNoMarkers = 75;
 xlAreaStacked = 76;
 xlAreaStacked100 = 77;
 xl3DAreaStacked = 78;
 xl3DAreaStacked100 = 79;
 xlDoughnutExploded = 80;
 xlRadarMarkers = 81;
 xlRadarFilled = 82;
 xlSurface = 83;
 xlSurfaceWireframe = 84;
 xlSurfaceTopView = 85;
 xlSurfaceTopViewWireframe = 86;
 xlBubble = 15;
 xlBubble3DEffect = 87;
 xlStockHLC = 88;
 xlStockOHLC = 89;
 xlStockVHLC = 90;
 xlStockVOHLC = 91;
 xlCylinderColClustered = 92;
 xlCylinderColStacked = 93;
 xlCylinderColStacked100 = 94;
 xlCylinderBarClustered = 95;
 xlCylinderBarStacked = 96;
 xlCylinderBarStacked100 = 97;
 xlCylinderCol = 98;
 xlConeColClustered = 99;
 xlConeColStacked = 100;
 xlConeColStacked100 = 101;
 xlConeBarClustered = 102;
 xlConeBarStacked = 103;
 xlConeBarStacked100 = 104;
 xlConeCol = 105;
 xlPyramidColClustered = 106;
 xlPyramidColStacked = 107;
 xlPyramidColStacked100 = 108;
 xlPyramidBarClustered = 109;
 xlPyramidBarStacked = 110;
 xlPyramidBarStacked100 = 111;
 xlPyramidCol = 112;
 xl3DColumn = -4100;
 xlLine = 4;
 xl3DLine = -4101;
 xl3DPie = -4102;
 xlPie = 5;
 xlXYScatter = -4169;
 xl3DArea = -4098;
 xlArea = 1;
 xlDoughnut = -4120;
 xlRadar = -4151;
{XlBarShape}
 xlBox = 0;
 xlPyramidToPoint = 1;
 xlPyramidToMax = 2;
 xlCylinder = 3;
 xlConeToPoint = 4;
 xlConeToMax = 5;
{XlSheetType}
 xlChart = -4109;
 xlDialogSheet = -4116;
 xlExcel4IntlMacroSheet = 4;
 xlExcel4MacroSheet = 3;
 xlWorksheet = -4167;
 xlCellValue = 1;
 xlEqual = 3;
 xlGreater = 5 ;
 xlLess = 6;
 xlGreaterEqual = 7;
 xlLessEqual = 8;
 {XlLineStyle}
 xlContinuous=1;
 xlDash=2;
 xlDashDot=3;
 xlDashDotDot=4;
 xlDot=5;
 xlDouble=6;
 xlSlantDashDot=7;
 xlLineStyleNone=8;

 // Excel Borders.Weight
  xlHairline = $00000001;
  xlMedium = $FFFFEFD6;
  xlThick = $00000004;
  xlThin = $00000002;

  // Excel Borders.Item()
  xlInsideHorizontal = $0000000C;
  xlInsideVertical = $0000000B;
  xlDiagonalDown = $00000005;
  xlDiagonalUp = $00000006;
  xlEdgeBottom = $00000009;
  xlEdgeLeft = $00000007;
  xlEdgeRight = $0000000A;
  xlEdgeTop = $00000008;

{Need an Excel 9 constants file? Note, for speed, use only the ones you need.

 Does the above mean runtime speed or compile time speed or both? David Fung
 Actually, it's speed to open forms/classes that include the file. Certainly, there's no runtime effect since constants are replaced at compile time.--TamarGranor

2005/02/17 Steven Blake - Current Microsoft Excel Constants web page
 2007/08/30 Mike Mohr - Excel 2003 Constants MSDN Library
 2007/08/30 Mike Mohr - Excel 2007 (office 12) Constants MSDN Library
#DEFINE xl24HourClock 33
 #DEFINE xl3DArea -4098
 #DEFINE xl3DAreaStacked 78
 #DEFINE xl3DAreaStacked100 79
 #DEFINE xl3DBar -4099
 #DEFINE xl3DBarClustered 60
 #DEFINE xl3DBarStacked 61
 #DEFINE xl3DBarStacked100 62
 #DEFINE xl3DColumn -4100
 #DEFINE xl3DColumnClustered 54
 #DEFINE xl3DColumnStacked 55
 #DEFINE xl3DColumnStacked100 56
 #DEFINE xl3DEffects1 13
 #DEFINE xl3DEffects2 14
 #DEFINE xl3DLine -4101
 #DEFINE xl3DPie -4102
 #DEFINE xl3DPieExploded 70
 #DEFINE xl3DSurface -4103
 #DEFINE xl4DigitYears 43
 #DEFINE xlA1 1
 #DEFINE xlAbove 0
 #DEFINE xlAbsolute 1
 #DEFINE xlAbsRowRelColumn 2
 #DEFINE xlAccounting1 4
 #DEFINE xlAccounting2 5
 #DEFINE xlAccounting3 6
 #DEFINE xlAccounting4 17
 #DEFINE xlAdd 2
 #DEFINE xlAddIn 18
 #DEFINE xlADORecordset 7
 #DEFINE xlAll -4104
 #DEFINE xlAllAtOnce 2
 #DEFINE xlAllChanges 2
 #DEFINE xlAllExceptBorders 7
 #DEFINE xlAllFaces 7
 #DEFINE xlAllTables 2
 #DEFINE xlAlternateArraySeparator 16
 #DEFINE xlAlways 1
 #DEFINE xlAnd 1
 #DEFINE xlAnyGallery 23
 #DEFINE xlAnyKey 2
 #DEFINE xlArabicBothStrict 3
 #DEFINE xlArabicNone 0
 #DEFINE xlArabicStrictAlefHamza 1
 #DEFINE xlArabicStrictFinalYaa 2
 #DEFINE xlArea 1
 #DEFINE xlAreaStacked 76
 #DEFINE xlAreaStacked100 77
 #DEFINE xlArrangeStyleCascade 7
 #DEFINE xlArrangeStyleHorizontal -4128
 #DEFINE xlArrangeStyleTiled 1
 #DEFINE xlArrangeStyleVertical -4166
 #DEFINE xlArrowHeadLengthLong 3
 #DEFINE xlArrowHeadLengthMedium -4138
 #DEFINE xlArrowHeadLengthShort 1
 #DEFINE xlArrowHeadStyleClosed 3
 #DEFINE xlArrowHeadStyleDoubleClosed 5
 #DEFINE xlArrowHeadStyleDoubleOpen 4
 #DEFINE xlArrowHeadStyleNone -4142
 #DEFINE xlArrowHeadStyleOpen 2
 #DEFINE xlArrowHeadWidthMedium -4138
 #DEFINE xlArrowHeadWidthNarrow 1
 #DEFINE xlArrowHeadWidthWide 3
 #DEFINE xlAscending 1
 #DEFINE xlAsRequired 0
 #DEFINE xlAtBottom 2
 #DEFINE xlAtTop 1
 #DEFINE xlAutoActivate 3
 #DEFINE xlAutoClose 2
 #DEFINE xlAutoDeactivate 4
 #DEFINE xlAutoFill 4
 #DEFINE xlAutomatic -4105
 #DEFINE xlAutomaticScale -4105
 #DEFINE xlAutomaticUpdate 4
 #DEFINE xlAutoOpen 1
 #DEFINE xlAverage -4106
 #DEFINE xlAxis 21
 #DEFINE xlAxisCrossesAutomatic -4105
 #DEFINE xlAxisCrossesCustom -4114
 #DEFINE xlAxisCrossesMaximum 2
 #DEFINE xlAxisCrossesMinimum 4
 #DEFINE xlAxisTitle 17
 #DEFINE xlBackgroundAutomatic -4105
 #DEFINE xlBackgroundOpaque 3
 #DEFINE xlBackgroundTransparent 2
 #DEFINE xlBar 2
 #DEFINE xlBarClustered 57
 #DEFINE xlBarOfPie 71
 #DEFINE xlBarStacked 58
 #DEFINE xlBarStacked100 59
 #DEFINE xlBelow 1
 #DEFINE xlBetween 1
 #DEFINE xlBidi -5000
 #DEFINE xlBidiCalendar 3
 #DEFINE xlBIFF 2
 #DEFINE xlBitmap 2
 #DEFINE xlBlanks 4
 #DEFINE xlBMP 1
 #DEFINE xlBoth 1
 #DEFINE xlBottom -4107
 #DEFINE xlBottom10Items 4
 #DEFINE xlBottom10Percent 6
 #DEFINE xlBox 0
 #DEFINE xlBubble 15
 #DEFINE xlBubble3DEffect 87
 #DEFINE xlBuiltIn 21
 #DEFINE xlButton 15
 #DEFINE xlButtonControl 0
 #DEFINE xlButtonOnly 2
 #DEFINE xlByColumns 2
 #DEFINE xlByRows 1
 #DEFINE xlCalculatedMember 0
 #DEFINE xlCalculatedSet 1
 #DEFINE xlCalculating 1
 #DEFINE xlCalculationAutomatic -4105
 #DEFINE xlCalculationManual -4135
 #DEFINE xlCalculationSemiautomatic 2
 #DEFINE xlCancel 1
 #DEFINE xlCap 1
 #DEFINE xlCascade 7
 #DEFINE xlCategory 1
 #DEFINE xlCategoryScale 2
 #DEFINE xlCellTypeAllFormatConditions -4172
 #DEFINE xlCellTypeAllValidation -4174
 #DEFINE xlCellTypeBlanks 4
 #DEFINE xlCellTypeComments -4144
 #DEFINE xlCellTypeConstants 2
 #DEFINE xlCellTypeFormulas -4123
 #DEFINE xlCellTypeLastCell 11
 #DEFINE xlCellTypeSameFormatConditions -4173
 #DEFINE xlCellTypeSameValidation -4175
 #DEFINE xlCellTypeVisible 12
 #DEFINE xlCellValue 1
 #DEFINE xlCenter -4108
 #DEFINE xlCenterAcrossSelection 7
 #DEFINE xlCGM 7
 #DEFINE xlChangeAttributes 6
 #DEFINE xlChart -4109
 #DEFINE xlChart4 2
 #DEFINE xlChartArea 2
 #DEFINE xlChartArea 2
 #DEFINE xlChartAsWindow 5
 #DEFINE xlChartInPlace 4
 #DEFINE xlChartSeries 17
 #DEFINE xlChartShort 6
 #DEFINE xlChartTitle 4
 #DEFINE xlChartTitles 18
 #DEFINE xlCheckBox 1
 #DEFINE xlChecker 9
 #DEFINE xlChronological 3
 #DEFINE xlCircle 8
 #DEFINE xlClassic1 1
 #DEFINE xlClassic2 2
 #DEFINE xlClassic3 3
 #DEFINE xlClipboard 3
 #DEFINE xlClipboardFormatBIFF 8
 #DEFINE xlClipboardFormatBIFF2 18
 #DEFINE xlClipboardFormatBIFF3 20
 #DEFINE xlClipboardFormatBIFF4 30
 #DEFINE xlClipboardFormatBinary 15
 #DEFINE xlClipboardFormatBitmap 9
 #DEFINE xlClipboardFormatCGM 13
 #DEFINE xlClipboardFormatCSV 5
 #DEFINE xlClipboardFormatDIF 4
 #DEFINE xlClipboardFormatDspText 12
 #DEFINE xlClipboardFormatEmbeddedObject 21
 #DEFINE xlClipboardFormatEmbedSource 22
 #DEFINE xlClipboardFormatLink 11
 #DEFINE xlClipboardFormatLinkSource 23
 #DEFINE xlClipboardFormatLinkSourceDesc 32
 #DEFINE xlClipboardFormatMovie 24
 #DEFINE xlClipboardFormatNative 14
 #DEFINE xlClipboardFormatObjectDesc 31
 #DEFINE xlClipboardFormatObjectLink 19
 #DEFINE xlClipboardFormatOwnerLink 17
 #DEFINE xlClipboardFormatPICT 2
 #DEFINE xlClipboardFormatPrintPICT 3
 #DEFINE xlClipboardFormatRTF 7
 #DEFINE xlClipboardFormatScreenPICT 29
 #DEFINE xlClipboardFormatStandardFont 28
 #DEFINE xlClipboardFormatStandardScale 27
 #DEFINE xlClipboardFormatSYLK 6
 #DEFINE xlClipboardFormatTable 16
 #DEFINE xlClipboardFormatText 0
 #DEFINE xlClipboardFormatToolFace 25
 #DEFINE xlClipboardFormatToolFacePICT 26
 #DEFINE xlClipboardFormatVALU 1
 #DEFINE xlClipboardFormatWK1 10
 #DEFINE xlClosed 3
 #DEFINE xlCmdCube 1
 #DEFINE xlCmdDefault 4
 #DEFINE xlCmdList 5
 #DEFINE xlCmdSql 2
 #DEFINE xlCmdTable 3
 #DEFINE xlCodePage 2
 #DEFINE xlColor1 7
 #DEFINE xlColor2 8
 #DEFINE xlColor3 9
 #DEFINE xlColorIndexAutomatic -4105
 #DEFINE xlColorIndexNone -4142
 #DEFINE xlColumn 3
 #DEFINE xlColumnClustered 51
 #DEFINE xlColumnField 2
 #DEFINE xlColumnHeader -4110
 #DEFINE xlColumnItem 5
 #DEFINE xlColumnLabels 2
 #DEFINE xlColumns 2
 #DEFINE xlColumnSeparator 14
 #DEFINE xlColumnStacked 52
 #DEFINE xlColumnStacked100 53
 #DEFINE xlColumnThenRow 2
 #DEFINE xlCombination -4111
 #DEFINE xlCommand 2
 #DEFINE xlCommandUnderlinesAutomatic -4105
 #DEFINE xlCommandUnderlinesOff -4146
 #DEFINE xlCommandUnderlinesOn 1
 #DEFINE xlCommentAndIndicator 1
 #DEFINE xlCommentIndicatorOnly -1
 #DEFINE xlComments -4144
 #DEFINE xlComplete 4
 #DEFINE xlConeBarClustered 102
 #DEFINE xlConeBarStacked 103
 #DEFINE xlConeBarStacked100 104
 #DEFINE xlConeCol 105
 #DEFINE xlConeColClustered 99
 #DEFINE xlConeColStacked 100
 #DEFINE xlConeColStacked100 101
 #DEFINE xlConeToMax 5
 #DEFINE xlConeToPoint 4
 #DEFINE xlConsolidation 3
 #DEFINE xlConstant 1
 #DEFINE xlConstants 2
 #DEFINE xlContents 2
 #DEFINE xlContext -5002
 #DEFINE xlContinuous 1
 #DEFINE xlCopy 1
 #DEFINE xlCorner 2
 #DEFINE xlCorners 6
 #DEFINE xlCount -4112
 #DEFINE xlCountNums -4113
 #DEFINE xlCountryCode 1
 #DEFINE xlCountrySetting 2
 #DEFINE xlCreatorCode 1480803660
 #DEFINE xlCrissCross 16
 #DEFINE xlCross 4
 #DEFINE xlCSV 6
 #DEFINE xlCSVMac 22
 #DEFINE xlCSVMSDOS 24
 #DEFINE xlCSVWindows 23
 #DEFINE xlCurrencyBefore 37
 #DEFINE xlCurrencyCode 25
 #DEFINE xlCurrencyDigits 27
 #DEFINE xlCurrencyLeadingZeros 40
 #DEFINE xlCurrencyMinusSign 38
 #DEFINE xlCurrencyNegative 28
 #DEFINE xlCurrencySpaceBefore 36
 #DEFINE xlCurrencyTrailingZeros 39
 #DEFINE xlCurrentPlatformText -4158
 #DEFINE xlCustom -4114
 #DEFINE xlCut 2
 #DEFINE xlCylinder 3
 #DEFINE xlCylinderBarClustered 95
 #DEFINE xlCylinderBarStacked 96
 #DEFINE xlCylinderBarStacked100 97
 #DEFINE xlCylinderCol 98
 #DEFINE xlCylinderColClustered 92
 #DEFINE xlCylinderColStacked 93
 #DEFINE xlCylinderColStacked100 94
 #DEFINE xlDAORecordset 2
 #DEFINE xlDash -4115
 #DEFINE xlDashDot 4
 #DEFINE xlDashDotDot 5
 #DEFINE xlDataAndLabel 0
 #DEFINE xlDatabase 1
 #DEFINE xlDataField 4
 #DEFINE xlDataHeader 3
 #DEFINE xlDataItem 7
 #DEFINE xlDataLabel 0
 #DEFINE xlDataLabelSeparatorDefault 1
 #DEFINE xlDataLabelsShowBubbleSizes 6
 #DEFINE xlDataLabelsShowLabel 4
 #DEFINE xlDataLabelsShowLabelAndPercent 5
 #DEFINE xlDataLabelsShowNone -4142
 #DEFINE xlDataLabelsShowPercent 3
 #DEFINE xlDataLabelsShowValue 2
 #DEFINE xlDataOnly 2
 #DEFINE xlDataSeriesLinear -4132
 #DEFINE xlDataTable 7
 #DEFINE xlDate 2
 #DEFINE xlDateOrder 32
 #DEFINE xlDateSeparator 17
 #DEFINE xlDay 1
 #DEFINE xlDayCode 21
 #DEFINE xlDayLeadingZero 42
 #DEFINE xlDays 0
 #DEFINE xlDBF2 7
 #DEFINE xlDBF3 8
 #DEFINE xlDBF4 11
 #DEFINE xlDebugCodePane 13
 #DEFINE xlDecimalSeparator 3
 #DEFINE xlDefault -4143
 #DEFINE xlDefaultAutoFormat -1
 #DEFINE xlDelimited 1
 #DEFINE xlDescending 2
 #DEFINE xlDesktop 9
 #DEFINE xlDiagonalDown 5
 #DEFINE xlDiagonalUp 6
 #DEFINE xlDialogActivate 103
 #DEFINE xlDialogActiveCellFont 476
 #DEFINE xlDialogAddChartAutoformat 390
 #DEFINE xlDialogAddinManager 321
 #DEFINE xlDialogAlignment 43
 #DEFINE xlDialogApplyNames 133
 #DEFINE xlDialogApplyStyle 212
 #DEFINE xlDialogAppMove 170
 #DEFINE xlDialogAppSize 171
 #DEFINE xlDialogArrangeAll 12
 #DEFINE xlDialogAssignToObject 213
 #DEFINE xlDialogAssignToTool 293
 #DEFINE xlDialogAttachText 80
 #DEFINE xlDialogAttachToolbars 323
 #DEFINE xlDialogAutoCorrect 485
 #DEFINE xlDialogAxes 78
 #DEFINE xlDialogBorder 45
 #DEFINE xlDialogCalculation 32
 #DEFINE xlDialogCellProtection 46
 #DEFINE xlDialogChangeLink 166
 #DEFINE xlDialogChartAddData 392
 #DEFINE xlDialogChartLocation 527
 #DEFINE xlDialogChartOptionsDataLabelMultiple 724
 #DEFINE xlDialogChartOptionsDataLabels 505
 #DEFINE xlDialogChartOptionsDataTable 506
 #DEFINE xlDialogChartSourceData 540
 #DEFINE xlDialogChartTrend 350
 #DEFINE xlDialogChartType 526
 #DEFINE xlDialogChartWizard 288
 #DEFINE xlDialogCheckboxProperties 435
 #DEFINE xlDialogClear 52
 #DEFINE xlDialogColorPalette 161
 #DEFINE xlDialogColumnWidth 47
 #DEFINE xlDialogCombination 73
 #DEFINE xlDialogConditionalFormatting 583
 #DEFINE xlDialogConsolidate 191
 #DEFINE xlDialogCopyChart 147
 #DEFINE xlDialogCopyPicture 108
 #DEFINE xlDialogCreateList 796
 #DEFINE xlDialogCreateNames 62
 #DEFINE xlDialogCreatePublisher 217
 #DEFINE xlDialogCustomizeToolbar 276
 #DEFINE xlDialogCustomViews 493
 #DEFINE xlDialogDataDelete 36
 #DEFINE xlDialogDataLabel 379
 #DEFINE xlDialogDataLabelMultiple 723
 #DEFINE xlDialogDataSeries 40
 #DEFINE xlDialogDataValidation 525
 #DEFINE xlDialogDefineName 61
 #DEFINE xlDialogDefineStyle 229
 #DEFINE xlDialogDeleteFormat 111
 #DEFINE xlDialogDeleteName 110
 #DEFINE xlDialogDemote 203
 #DEFINE xlDialogDisplay 27
 #DEFINE xlDialogEditboxProperties 438
 #DEFINE xlDialogEditColor 223
 #DEFINE xlDialogEditDelete 54
 #DEFINE xlDialogEditionOptions 251
 #DEFINE xlDialogEditSeries 228
 #DEFINE xlDialogErrorbarX 463
 #DEFINE xlDialogErrorbarY 464
 #DEFINE xlDialogErrorChecking 732
 #DEFINE xlDialogEvaluateFormula 709
 #DEFINE xlDialogExternalDataProperties 530
 #DEFINE xlDialogExtract 35
 #DEFINE xlDialogFileDelete 6
 #DEFINE xlDialogFileSharing 481
 #DEFINE xlDialogFillGroup 200
 #DEFINE xlDialogFillWorkgroup 301
 #DEFINE xlDialogFilter 447
 #DEFINE xlDialogFilterAdvanced 370
 #DEFINE xlDialogFindFile 475
 #DEFINE xlDialogFont 26
 #DEFINE xlDialogFontProperties 381
 #DEFINE xlDialogFormatAuto 269
 #DEFINE xlDialogFormatChart 465
 #DEFINE xlDialogFormatCharttype 423
 #DEFINE xlDialogFormatFont 150
 #DEFINE xlDialogFormatLegend 88
 #DEFINE xlDialogFormatMain 225
 #DEFINE xlDialogFormatMove 128
 #DEFINE xlDialogFormatNumber 42
 #DEFINE xlDialogFormatOverlay 226
 #DEFINE xlDialogFormatSize 129
 #DEFINE xlDialogFormatText 89
 #DEFINE xlDialogFormulaFind 64
 #DEFINE xlDialogFormulaGoto 63
 #DEFINE xlDialogFormulaReplace 130
 #DEFINE xlDialogFunctionWizard 450
 #DEFINE xlDialogGallery3dArea 193
 #DEFINE xlDialogGallery3dBar 272
 #DEFINE xlDialogGallery3dColumn 194
 #DEFINE xlDialogGallery3dLine 195
 #DEFINE xlDialogGallery3dPie 196
 #DEFINE xlDialogGallery3dSurface 273
 #DEFINE xlDialogGalleryArea 67
 #DEFINE xlDialogGalleryBar 68
 #DEFINE xlDialogGalleryColumn 69
 #DEFINE xlDialogGalleryCustom 388
 #DEFINE xlDialogGalleryDoughnut 344
 #DEFINE xlDialogGalleryLine 70
 #DEFINE xlDialogGalleryPie 71
 #DEFINE xlDialogGalleryRadar 249
 #DEFINE xlDialogGalleryScatter 72
 #DEFINE xlDialogGoalSeek 198
 #DEFINE xlDialogGridlines 76
 #DEFINE xlDialogImportTextFile 666
 #DEFINE xlDialogInsert 55
 #DEFINE xlDialogInsertHyperlink 596
 #DEFINE xlDialogInsertNameLabel 496
 #DEFINE xlDialogInsertObject 259
 #DEFINE xlDialogInsertPicture 342
 #DEFINE xlDialogInsertTitle 380
 #DEFINE xlDialogLabelProperties 436
 #DEFINE xlDialogListboxProperties 437
 #DEFINE xlDialogMacroOptions 382
 #DEFINE xlDialogMailEditMailer 470
 #DEFINE xlDialogMailLogon 339
 #DEFINE xlDialogMailNextLetter 378
 #DEFINE xlDialogMainChart 85
 #DEFINE xlDialogMainChartType 185
 #DEFINE xlDialogMenuEditor 322
 #DEFINE xlDialogMove 262
 #DEFINE xlDialogMyPermission 834
 #DEFINE xlDialogNew 119
 #DEFINE xlDialogNewWebQuery 667
 #DEFINE xlDialogNote 154
 #DEFINE xlDialogObjectProperties 207
 #DEFINE xlDialogObjectProtection 214
 #DEFINE xlDialogOpen 1
 #DEFINE xlDialogOpenLinks 2
 #DEFINE xlDialogOpenMail 188
 #DEFINE xlDialogOpenText 441
 #DEFINE xlDialogOptionsCalculation 318
 #DEFINE xlDialogOptionsChart 325
 #DEFINE xlDialogOptionsEdit 319
 #DEFINE xlDialogOptionsGeneral 356
 #DEFINE xlDialogOptionsListsAdd 458
 #DEFINE xlDialogOptionsME 647
 #DEFINE xlDialogOptionsTransition 355
 #DEFINE xlDialogOptionsView 320
 #DEFINE xlDialogOutline 142
 #DEFINE xlDialogOverlay 86
 #DEFINE xlDialogOverlayChartType 186
 #DEFINE xlDialogPageSetup 7
 #DEFINE xlDialogParse 91
 #DEFINE xlDialogPasteNames 58
 #DEFINE xlDialogPasteSpecial 53
 #DEFINE xlDialogPatterns 84
 #DEFINE xlDialogPermission 832
 #DEFINE xlDialogPhonetic 656
 #DEFINE xlDialogPivotCalculatedField 570
 #DEFINE xlDialogPivotCalculatedItem 572
 #DEFINE xlDialogPivotClientServerSet 689
 #DEFINE xlDialogPivotFieldGroup 433
 #DEFINE xlDialogPivotFieldProperties 313
 #DEFINE xlDialogPivotFieldUngroup 434
 #DEFINE xlDialogPivotShowPages 421
 #DEFINE xlDialogPivotSolveOrder 568
 #DEFINE xlDialogPivotTableOptions 567
 #DEFINE xlDialogPivotTableWizard 312
 #DEFINE xlDialogPlacement 300
 #DEFINE xlDialogPrint 8
 #DEFINE xlDialogPrinterSetup 9
 #DEFINE xlDialogPrintPreview 222
 #DEFINE xlDialogPromote 202
 #DEFINE xlDialogProperties 474
 #DEFINE xlDialogPropertyFields 754
 #DEFINE xlDialogProtectDocument 28
 #DEFINE xlDialogProtectSharing 620
 #DEFINE xlDialogPublishAsWebPage 653
 #DEFINE xlDialogPushbuttonProperties 445
 #DEFINE xlDialogReplaceFont 134
 #DEFINE xlDialogRoutingSlip 336
 #DEFINE xlDialogRowHeight 127
 #DEFINE xlDialogRun 17
 #DEFINE xlDialogSaveAs 5
 #DEFINE xlDialogSaveCopyAs 456
 #DEFINE xlDialogSaveNewObject 208
 #DEFINE xlDialogSaveWorkbook 145
 #DEFINE xlDialogSaveWorkspace 285
 #DEFINE xlDialogScale 87
 #DEFINE xlDialogScenarioAdd 307
 #DEFINE xlDialogScenarioCells 305
 #DEFINE xlDialogScenarioEdit 308
 #DEFINE xlDialogScenarioMerge 473
 #DEFINE xlDialogScenarioSummary 311
 #DEFINE xlDialogScrollbarProperties 420
 #DEFINE xlDialogSearch 731
 #DEFINE xlDialogSelectSpecial 132
 #DEFINE xlDialogSendMail 189
 #DEFINE xlDialogSeriesAxes 460
 #DEFINE xlDialogSeriesOptions 557
 #DEFINE xlDialogSeriesOrder 466
 #DEFINE xlDialogSeriesShape 504
 #DEFINE xlDialogSeriesX 461
 #DEFINE xlDialogSeriesY 462
 #DEFINE xlDialogSetBackgroundPicture 509
 #DEFINE xlDialogSetPrintTitles 23
 #DEFINE xlDialogSetUpdateStatus 159
 #DEFINE xlDialogSheet -4116
 #DEFINE xlDialogShowDetail 204
 #DEFINE xlDialogShowToolbar 220
 #DEFINE xlDialogSize 261
 #DEFINE xlDialogSort 39
 #DEFINE xlDialogSortSpecial 192
 #DEFINE xlDialogSplit 137
 #DEFINE xlDialogStandardFont 190
 #DEFINE xlDialogStandardWidth 472
 #DEFINE xlDialogStyle 44
 #DEFINE xlDialogSubscribeTo 218
 #DEFINE xlDialogSubtotalCreate 398
 #DEFINE xlDialogSummaryInfo 474
 #DEFINE xlDialogTable 41
 #DEFINE xlDialogTabOrder 394
 #DEFINE xlDialogTextToColumns 422
 #DEFINE xlDialogUnhide 94
 #DEFINE xlDialogUpdateLink 201
 #DEFINE xlDialogVbaInsertFile 328
 #DEFINE xlDialogVbaMakeAddin 478
 #DEFINE xlDialogVbaProcedureDefinition 330
 #DEFINE xlDialogView3d 197
 #DEFINE xlDialogWebOptionsBrowsers 773
 #DEFINE xlDialogWebOptionsEncoding 686
 #DEFINE xlDialogWebOptionsFiles 684
 #DEFINE xlDialogWebOptionsFonts 687
 #DEFINE xlDialogWebOptionsGeneral 683
 #DEFINE xlDialogWebOptionsPictures 685
 #DEFINE xlDialogWindowMove 14
 #DEFINE xlDialogWindowSize 13
 #DEFINE xlDialogWorkbookAdd 281
 #DEFINE xlDialogWorkbookCopy 283
 #DEFINE xlDialogWorkbookInsert 354
 #DEFINE xlDialogWorkbookMove 282
 #DEFINE xlDialogWorkbookName 386
 #DEFINE xlDialogWorkbookNew 302
 #DEFINE xlDialogWorkbookOptions 284
 #DEFINE xlDialogWorkbookProtect 417
 #DEFINE xlDialogWorkbookTabSplit 415
 #DEFINE xlDialogWorkbookUnhide 384
 #DEFINE xlDialogWorkgroup 199
 #DEFINE xlDialogWorkspace 95
 #DEFINE xlDialogZoom 256
 #DEFINE xlDiamond 2
 #DEFINE xlDIF 9
 #DEFINE xlDifferenceFrom 2
 #DEFINE xlDirect 1
 #DEFINE xlDisabled 0
 #DEFINE xlDisplayNone 1
 #DEFINE xlDisplayShapes -4104
 #DEFINE xlDisplayUnitLabel 30
 #DEFINE xlDistributed -4117
 #DEFINE xlDivide 5
 #DEFINE xlDMYFormat 4
 #DEFINE xlDone 0
 #DEFINE xlDoNotSaveChanges 2
 #DEFINE xlDot -4118
 #DEFINE xlDouble -4119
 #DEFINE xlDoubleAccounting 5
 #DEFINE xlDoubleClosed 5
 #DEFINE xlDoubleOpen 4
 #DEFINE xlDoubleQuote 1
 #DEFINE xlDoughnut -4120
 #DEFINE xlDoughnutExploded 80
 #DEFINE xlDown -4121
 #DEFINE xlDownBars 20
 #DEFINE xlDownThenOver 1
 #DEFINE xlDownward -4170
 #DEFINE xlDrawingObject 14
 #DEFINE xlDropDown 2
 #DEFINE xlDropLines 26
 #DEFINE xlDRW 4
 #DEFINE xlDXF 5
 #DEFINE xlDYMFormat 7
 #DEFINE xlEdgeBottom 9
 #DEFINE xlEdgeLeft 7
 #DEFINE xlEdgeRight 10
 #DEFINE xlEdgeTop 8
 #DEFINE xlEditBox 3
 #DEFINE xlEditionDate 2
 #DEFINE xlEMDFormat 10
 #DEFINE xlEmptyCellReferences 7
 #DEFINE xlEnd 2
 #DEFINE xlEndSides 3
 #DEFINE xlEntireChart 20
 #DEFINE xlEntirePage 1
 #DEFINE xlEPS 8
 #DEFINE xlEqual 3
 #DEFINE xlErrDiv0 2007
 #DEFINE xlErrNA 2042
 #DEFINE xlErrName 2029
 #DEFINE xlErrNull 2000
 #DEFINE xlErrNum 2036
 #DEFINE xlErrorBarIncludeBoth 1
 #DEFINE xlErrorBarIncludeMinusValues 3
 #DEFINE xlErrorBarIncludeNone -4142
 #DEFINE xlErrorBarIncludePlusValues 2
 #DEFINE xlErrorBars 9
 #DEFINE xlErrorBarTypeCustom -4114
 #DEFINE xlErrorBarTypeFixedValue 1
 #DEFINE xlErrorBarTypePercent 2
 #DEFINE xlErrorBarTypeStDev -4155
 #DEFINE xlErrorBarTypeStError 4
 #DEFINE xlErrorHandler 2
 #DEFINE xlErrors 16
 #DEFINE xlErrRef 2023
 #DEFINE xlErrValue 2015
 #DEFINE xlEscKey 1
 #DEFINE xlEvaluateToError 1
 #DEFINE xlExcel2 16
 #DEFINE xlExcel2FarEast 27
 #DEFINE xlExcel3 29
 #DEFINE xlExcel4 33
 #DEFINE xlExcel4IntlMacroSheet 4
 #DEFINE xlExcel4MacroSheet 3
 #DEFINE xlExcel4Workbook 35
 #DEFINE xlExcel5 39
 #DEFINE xlExcel7 39
 #DEFINE xlExcel9795 43
 #DEFINE xlExcelLinks 1
 #DEFINE xlExcelMenus 1
 #DEFINE xlExclusive 3
 #DEFINE xlExponential 5
 #DEFINE xlExpression 2
 #DEFINE xlExtended 3
 #DEFINE xlExternal 2
 #DEFINE xlExtractData 2
 #DEFINE xlFill 5
 #DEFINE xlFillCopy 1
 #DEFINE xlFillDays 5
 #DEFINE xlFillDefault 0
 #DEFINE xlFillFormats 3
 #DEFINE xlFillMonths 7
 #DEFINE xlFillSeries 2
 #DEFINE xlFillValues 4
 #DEFINE xlFillWeekdays 6
 #DEFINE xlFillWithAll -4104
 #DEFINE xlFillWithContents 2
 #DEFINE xlFillWithFormats -4122
 #DEFINE xlFillYears 8
 #DEFINE xlFilterCopy 2
 #DEFINE xlFilterInPlace 1
 #DEFINE xlFirst 0
 #DEFINE xlFirstRow 256
 #DEFINE xlFitToPage 2
 #DEFINE xlFixedValue 1
 #DEFINE xlFixedWidth 2
 #DEFINE xlFloating 5
 #DEFINE xlFloor 23
 #DEFINE xlFormatFromLeftOrAbove 0
 #DEFINE xlFormatFromRightOrBelow 1
 #DEFINE xlFormats -4122
 #DEFINE xlFormula 5
 #DEFINE xlFormulas -4123
 #DEFINE xlFreeFloating 3
 #DEFINE xlFront 4
 #DEFINE xlFrontEnd 6
 #DEFINE xlFrontSides 5
 #DEFINE xlFullPage 3
 #DEFINE xlFullScript 1
 #DEFINE xlFunction 1
 #DEFINE xlGeneral 1
 #DEFINE xlGeneralFormat 1
 #DEFINE xlGeneralFormatName 26
 #DEFINE xlGray16 17
 #DEFINE xlGray25 -4124
 #DEFINE xlGray50 -4125
 #DEFINE xlGray75 -4126
 #DEFINE xlGray8 18
 #DEFINE xlGreater 5
 #DEFINE xlGreaterEqual 7
 #DEFINE xlGregorian 2
 #DEFINE xlGrid 15
 #DEFINE xlGridline 22
 #DEFINE xlGroupBox 4
 #DEFINE xlGrowth 2
 #DEFINE xlGrowthTrend 10
 #DEFINE xlGuess 0
 #DEFINE xlHairline 1
 #DEFINE xlHAlignCenter -4108
 #DEFINE xlHAlignCenterAcrossSelection 7
 #DEFINE xlHAlignDistributed -4117
 #DEFINE xlHAlignFill 5
 #DEFINE xlHAlignGeneral 1
 #DEFINE xlHAlignJustify -4130
 #DEFINE xlHAlignLeft -4131
 #DEFINE xlHAlignRight -4152
 #DEFINE xlHebrewFullScript 0
 #DEFINE xlHebrewMixedAuthorizedScript 3
 #DEFINE xlHebrewMixedScript 2
 #DEFINE xlHebrewPartialScript 1
 #DEFINE xlHGL 6
 #DEFINE xlHidden 0
 #DEFINE xlHide 3
 #DEFINE xlHierarchy 1
 #DEFINE xlHigh -4127
 #DEFINE xlHiLoLines 25
 #DEFINE xlHindiNumerals 3
 #DEFINE xlHiragana 2
 #DEFINE xlHorizontal -4128
 #DEFINE xlHourCode 22
 #DEFINE xlHtml 44
 #DEFINE xlHtmlCalc 1
 #DEFINE xlHtmlChart 3
 #DEFINE xlHtmlList 2
 #DEFINE xlHtmlStatic 0
 #DEFINE xlHundredMillions -8
 #DEFINE xlHundreds -2
 #DEFINE xlHundredThousands -5
 #DEFINE xlIBeam 3
 #DEFINE xlIcons 1
 #DEFINE xlIMEModeAlpha 8
 #DEFINE xlIMEModeAlphaFull 7
 #DEFINE xlIMEModeDisable 3
 #DEFINE xlIMEModeHangul 10
 #DEFINE xlIMEModeHangulFull 9
 #DEFINE xlIMEModeHiragana 4
 #DEFINE xlIMEModeKatakana 5
 #DEFINE xlIMEModeKatakanaHalf 6
 #DEFINE xlIMEModeNoControl 0
 #DEFINE xlIMEModeOff 2
 #DEFINE xlIMEModeOn 1
 #DEFINE xlImmediatePane 12
 #DEFINE xlInconsistentFormula 4
 #DEFINE xlIndex 9
 #DEFINE xlIndicatorAndButton 0
 #DEFINE xlInfo -4129
 #DEFINE xlInsertDeleteCells 1
 #DEFINE xlInsertEntireRows 2
 #DEFINE xlInside 2
 #DEFINE xlInsideHorizontal 12
 #DEFINE xlInsideVertical 11
 #DEFINE xlInteger 2
 #DEFINE xlInterpolated 3
 #DEFINE xlInterrupt 1
 #DEFINE xlIntlAddIn 26
 #DEFINE xlIntlMacro 25
 #DEFINE xlJustify -4130
 #DEFINE xlKatakana 1
 #DEFINE xlKatakanaHalf 0
 #DEFINE xlLabel 5
 #DEFINE xlLabelOnly 1
 #DEFINE xlLabelPositionAbove 0
 #DEFINE xlLabelPositionBelow 1
 #DEFINE xlLabelPositionBestFit 5
 #DEFINE xlLabelPositionCenter -4108
 #DEFINE xlLabelPositionCustom 7
 #DEFINE xlLabelPositionInsideBase 4
 #DEFINE xlLabelPositionInsideEnd 3
 #DEFINE xlLabelPositionLeft -4131
 #DEFINE xlLabelPositionMixed 6
 #DEFINE xlLabelPositionOutsideEnd 2
 #DEFINE xlLabelPositionRight -4152
 #DEFINE xlLandscape 2
 #DEFINE xlLast 1
 #DEFINE xlLastCell 11
 #DEFINE xlLatin -5001
 #DEFINE xlLeaderLines 29
 #DEFINE xlLeft -4131
 #DEFINE xlLeftBrace 12
 #DEFINE xlLeftBracket 10
 #DEFINE xlLeftToRight 2
 #DEFINE xlLegend 24
 #DEFINE xlLegendEntry 12
 #DEFINE xlLegendKey 13
 #DEFINE xlLegendPositionBottom -4107
 #DEFINE xlLegendPositionCorner 2
 #DEFINE xlLegendPositionLeft -4131
 #DEFINE xlLegendPositionRight -4152
 #DEFINE xlLegendPositionTop -4160
 #DEFINE xlLess 6
 #DEFINE xlLessEqual 8
 #DEFINE xlLightDown 13
 #DEFINE xlLightHorizontal 11
 #DEFINE xlLightUp 14
 #DEFINE xlLightVertical 12
 #DEFINE xlLine 4
 #DEFINE xlLinear -4132
 #DEFINE xlLinearTrend 9
 #DEFINE xlLineMarkers 65
 #DEFINE xlLineMarkersStacked 66
 #DEFINE xlLineMarkersStacked100 67
 #DEFINE xlLineStacked 63
 #DEFINE xlLineStacked100 64
 #DEFINE xlLineStyleNone -4142
 #DEFINE xlLinkInfoOLELinks 2
 #DEFINE xlLinkInfoPublishers 5
 #DEFINE xlLinkInfoStatus 3
 #DEFINE xlLinkInfoSubscribers 6
 #DEFINE xlLinkStatusCopiedValues 10
 #DEFINE xlLinkStatusIndeterminate 5
 #DEFINE xlLinkStatusInvalidName 7
 #DEFINE xlLinkStatusMissingFile 1
 #DEFINE xlLinkStatusMissingSheet 2
 #DEFINE xlLinkStatusNotStarted 6
 #DEFINE xlLinkStatusOK 0
 #DEFINE xlLinkStatusOld 3
 #DEFINE xlLinkStatusSourceNotCalculated 4
 #DEFINE xlLinkStatusSourceNotOpen 8
 #DEFINE xlLinkStatusSourceOpen 9
 #DEFINE xlLinkTypeExcelLinks 1
 #DEFINE xlLinkTypeOLELinks 2
 #DEFINE xlList1 10
 #DEFINE xlList2 11
 #DEFINE xlList3 12
 #DEFINE xlListBox 6
 #DEFINE xlListConflictDialog 0
 #DEFINE xlListConflictDiscardAllConflicts 2
 #DEFINE xlListConflictError 3
 #DEFINE xlListConflictRetryAllConflicts 1
 #DEFINE xlListDataTypeCheckbox 9
 #DEFINE xlListDataTypeChoice 6
 #DEFINE xlListDataTypeChoiceMulti 7
 #DEFINE xlListDataTypeCounter 11
 #DEFINE xlListDataTypeCurrency 4
 #DEFINE xlListDataTypeDateTime 5
 #DEFINE xlListDataTypeHyperLink 10
 #DEFINE xlListDataTypeListLookup 8
 #DEFINE xlListDataTypeMultiLineRichText 12
 #DEFINE xlListDataTypeMultiLineText 2
 #DEFINE xlListDataTypeNone 0
 #DEFINE xlListDataTypeNumber 3
 #DEFINE xlListDataTypeText 1
 #DEFINE xlListDataValidation 8
 #DEFINE xlListSeparator 5
 #DEFINE xlLocalFormat1 15
 #DEFINE xlLocalFormat2 16
 #DEFINE xlLocalSessionChanges 2
 #DEFINE xlLocationAsNewSheet 1
 #DEFINE xlLocationAsObject 2
 #DEFINE xlLocationAutomatic 3
 #DEFINE xlLogarithmic -4133
 #DEFINE xlLogical 4
 #DEFINE xlLogicalCursor 1
 #DEFINE xlLong 3
 #DEFINE xlLotusHelp 2
 #DEFINE xlLow -4134
 #DEFINE xlLowerCaseColumnLetter 9
 #DEFINE xlLowerCaseRowLetter 8
 #DEFINE xlLTR -5003
 #DEFINE xlMacintosh 1
 #DEFINE xlMacrosheetCell 7
 #DEFINE xlMajorGridlines 15
 #DEFINE xlManual -4135
 #DEFINE xlManualUpdate 5
 #DEFINE xlMAPI 1
 #DEFINE xlMarkerStyleAutomatic -4105
 #DEFINE xlMarkerStyleCircle 8
 #DEFINE xlMarkerStyleDash -4115
 #DEFINE xlMarkerStyleDiamond 2
 #DEFINE xlMarkerStyleDot -4118
 #DEFINE xlMarkerStyleNone -4142
 #DEFINE xlMarkerStylePicture -4147
 #DEFINE xlMarkerStylePlus 9
 #DEFINE xlMarkerStyleSquare 1
 #DEFINE xlMarkerStyleStar 5
 #DEFINE xlMarkerStyleTriangle 3
 #DEFINE xlMarkerStyleX -4168
 #DEFINE xlMax -4136
 #DEFINE xlMaximized -4137
 #DEFINE xlMaximum 2
 #DEFINE xlMDY 44
 #DEFINE xlMDYFormat 3
 #DEFINE xlMeasure 2
 #DEFINE xlMedium -4138
 #DEFINE xlMetric 35
 #DEFINE xlMicrosoftAccess 4
 #DEFINE xlMicrosoftFoxPro 5
 #DEFINE xlMicrosoftMail 3
 #DEFINE xlMicrosoftPowerPoint 2
 #DEFINE xlMicrosoftProject 6
 #DEFINE xlMicrosoftSchedulePlus 7
 #DEFINE xlMicrosoftWord 1
 #DEFINE xlMillionMillions -10
 #DEFINE xlMillions -6
 #DEFINE xlMin -4139
 #DEFINE xlMinimized -4140
 #DEFINE xlMinimum 4
 #DEFINE xlMinorGridlines 16
 #DEFINE xlMinusValues 3
 #DEFINE xlMinuteCode 23
 #DEFINE xlMissingItemsDefault -1
 #DEFINE xlMissingItemsMax 32500
 #DEFINE xlMissingItemsNone 0
 #DEFINE xlMixed 2
 #DEFINE xlMixedAuthorizedScript 4
 #DEFINE xlMixedLabels 3
 #DEFINE xlMixedScript 3
 #DEFINE xlModule -4141
 #DEFINE xlMonth 3
 #DEFINE xlMonthCode 20
 #DEFINE xlMonthLeadingZero 41
 #DEFINE xlMonthNameChars 30
 #DEFINE xlMonths 1
 #DEFINE xlMove 2
 #DEFINE xlMoveAndSize 1
 #DEFINE xlMovingAvg 6
 #DEFINE xlMSDOS 3
 #DEFINE xlMultiply 4
 #DEFINE xlMYDFormat 6
 #DEFINE xlNarrow 1
 #DEFINE xlNever 2
 #DEFINE xlNext 1
 #DEFINE xlNextToAxis 4
 #DEFINE xlNo 2
 #DEFINE xlNoAdditionalCalculation -4143
 #DEFINE xlNoButton 0
 #DEFINE xlNoButtonChanges 1
 #DEFINE xlNoCap 2
 #DEFINE xlNoChange 1
 #DEFINE xlNoChanges 4
 #DEFINE xlNoConversion 3
 #DEFINE xlNoDockingChanges 3
 #DEFINE xlNoDocuments 3
 #DEFINE xlNoIndicator 0
 #DEFINE xlNoKey 0
 #DEFINE xlNoLabels -4142
 #DEFINE xlNoMailSystem 0
 #DEFINE xlNoncurrencyDigits 29
 #DEFINE xlNone -4142
 #DEFINE xlNonEnglishFunctions 34
 #DEFINE xlNoRestrictions 0
 #DEFINE xlNormal -4143
 #DEFINE xlNormalLoad 0
 #DEFINE xlNormalView 1
 #DEFINE xlNorthwestArrow 1
 #DEFINE xlNoSelection -4142
 #DEFINE xlNoShapeChanges 2
 #DEFINE xlNotBetween 2
 #DEFINE xlNotEqual 4
 #DEFINE xlNotes -4144
 #DEFINE xlNothing 28
 #DEFINE xlNotPlotted 1
 #DEFINE xlNotXLM 3
 #DEFINE xlNotYetReviewed 3
 #DEFINE xlNotYetRouted 0
 #DEFINE xlNumber -4145
 #DEFINE xlNumberAsText 3
 #DEFINE xlNumbers 1
 #DEFINE xlODBCQuery 1
 #DEFINE xlOff -4146
 #DEFINE xlOLEControl 2
 #DEFINE xlOLEDBQuery 5
 #DEFINE xlOLEEmbed 1
 #DEFINE xlOLELink 0
 #DEFINE xlOLELinks 2
 #DEFINE xlOmittedCells 5
 #DEFINE xlOn 1
 #DEFINE xlOneAfterAnother 1
 #DEFINE xlOpaque 3
 #DEFINE xlOpen 2
 #DEFINE xlOpenSource 3
 #DEFINE xlOptionButton 7
 #DEFINE xlOr 2
 #DEFINE xlOrigin 3
 #DEFINE xlOtherSessionChanges 3
 #DEFINE xlOutline 1
 #DEFINE xlOutside 3
 #DEFINE xlOverThenDown 2
 #DEFINE xlOverwriteCells 0
 #DEFINE xlPageBreakAutomatic -4105
 #DEFINE xlPageBreakFull 1
 #DEFINE xlPageBreakManual -4135
 #DEFINE xlPageBreakNone -4142
 #DEFINE xlPageBreakPartial 2
 #DEFINE xlPageBreakPreview 2
 #DEFINE xlPageField 3
 #DEFINE xlPageHeader 2
 #DEFINE xlPageItem 6
 #DEFINE xlPaper10x14 16
 #DEFINE xlPaper11x17 17
 #DEFINE xlPaperA3 8
 #DEFINE xlPaperA4 9
 #DEFINE xlPaperA4Small 10
 #DEFINE xlPaperA5 11
 #DEFINE xlPaperB4 12
 #DEFINE xlPaperB5 13
 #DEFINE xlPaperCsheet 24
 #DEFINE xlPaperDsheet 25
 #DEFINE xlPaperEnvelope10 20
 #DEFINE xlPaperEnvelope11 21
 #DEFINE xlPaperEnvelope12 22
 #DEFINE xlPaperEnvelope14 23
 #DEFINE xlPaperEnvelope9 19
 #DEFINE xlPaperEnvelopeB4 33
 #DEFINE xlPaperEnvelopeB5 34
 #DEFINE xlPaperEnvelopeB6 35
 #DEFINE xlPaperEnvelopeC3 29
 #DEFINE xlPaperEnvelopeC4 30
 #DEFINE xlPaperEnvelopeC5 28
 #DEFINE xlPaperEnvelopeC6 31
 #DEFINE xlPaperEnvelopeC65 32
 #DEFINE xlPaperEnvelopeDL 27
 #DEFINE xlPaperEnvelopeItaly 36
 #DEFINE xlPaperEnvelopeMonarch 37
 #DEFINE xlPaperEnvelopePersonal 38
 #DEFINE xlPaperEsheet 26
 #DEFINE xlPaperExecutive 7
 #DEFINE xlPaperFanfoldLegalGerman 41
 #DEFINE xlPaperFanfoldStdGerman 40
 #DEFINE xlPaperFanfoldUS 39
 #DEFINE xlPaperFolio 14
 #DEFINE xlPaperLedger 4
 #DEFINE xlPaperLegal 5
 #DEFINE xlPaperLetter 1
 #DEFINE xlPaperLetterSmall 2
 #DEFINE xlPaperNote 18
 #DEFINE xlPaperQuarto 15
 #DEFINE xlPaperStatement 6
 #DEFINE xlPaperTabloid 3
 #DEFINE xlPaperUser 256
 #DEFINE xlParamTypeBigInt -5
 #DEFINE xlParamTypeBinary -2
 #DEFINE xlParamTypeBit -7
 #DEFINE xlParamTypeChar 1
 #DEFINE xlParamTypeDate 9
 #DEFINE xlParamTypeDecimal 3
 #DEFINE xlParamTypeDouble 8
 #DEFINE xlParamTypeFloat 6
 #DEFINE xlParamTypeInteger 4
 #DEFINE xlParamTypeLongVarBinary -4
 #DEFINE xlParamTypeLongVarChar -1
 #DEFINE xlParamTypeNumeric 2
 #DEFINE xlParamTypeReal 7
 #DEFINE xlParamTypeSmallInt 5
 #DEFINE xlParamTypeTime 10
 #DEFINE xlParamTypeTimestamp 11
 #DEFINE xlParamTypeTinyInt -6
 #DEFINE xlParamTypeUnknown 0
 #DEFINE xlParamTypeVarBinary -3
 #DEFINE xlParamTypeVarChar 12
 #DEFINE xlParamTypeWChar -8
 #DEFINE xlPart 2
 #DEFINE xlPartial 3
 #DEFINE xlPartialScript 2
 #DEFINE xlPasteAll -4104
 #DEFINE xlPasteAllExceptBorders 7
 #DEFINE xlPasteColumnWidths 8
 #DEFINE xlPasteComments -4144
 #DEFINE xlPasteFormats -4122
 #DEFINE xlPasteFormulas -4123
 #DEFINE xlPasteFormulasAndNumberFormats 11
 #DEFINE xlPasteSpecialOperationAdd 2
 #DEFINE xlPasteSpecialOperationDivide 5
 #DEFINE xlPasteSpecialOperationMultiply 4
 #DEFINE xlPasteSpecialOperationNone -4142
 #DEFINE xlPasteSpecialOperationSubtract 3
 #DEFINE xlPasteValidation 6
 #DEFINE xlPasteValues -4163
 #DEFINE xlPasteValuesAndNumberFormats 12
 #DEFINE xlPatternAutomatic -4105
 #DEFINE xlPatternChecker 9
 #DEFINE xlPatternCrissCross 16
 #DEFINE xlPatternDown -4121
 #DEFINE xlPatternGray16 17
 #DEFINE xlPatternGray25 -4124
 #DEFINE xlPatternGray50 -4125
 #DEFINE xlPatternGray75 -4126
 #DEFINE xlPatternGray8 18
 #DEFINE xlPatternGrid 15
 #DEFINE xlPatternHorizontal -4128
 #DEFINE xlPatternLightDown 13
 #DEFINE xlPatternLightHorizontal 11
 #DEFINE xlPatternLightUp 14
 #DEFINE xlPatternLightVertical 12
 #DEFINE xlPatternNone -4142
 #DEFINE xlPatternSemiGray75 10
 #DEFINE xlPatternSolid 1
 #DEFINE xlPatternUp -4162
 #DEFINE xlPatternVertical -4166
 #DEFINE xlPCT 13
 #DEFINE xlPCX 10
 #DEFINE xlPending 2
 #DEFINE xlPercent 2
 #DEFINE xlPercentDifferenceFrom 4
 #DEFINE xlPercentOf 3
 #DEFINE xlPercentOfColumn 7
 #DEFINE xlPercentOfRow 6
 #DEFINE xlPercentOfTotal 8
 #DEFINE xlPhoneticAlignCenter 2
 #DEFINE xlPhoneticAlignDistributed 3
 #DEFINE xlPhoneticAlignLeft 1
 #DEFINE xlPhoneticAlignNoControl 0
 #DEFINE xlPIC 11
 #DEFINE xlPICT 1
 #DEFINE xlPicture -4147
 #DEFINE xlPie 5
 #DEFINE xlPieExploded 69
 #DEFINE xlPieOfPie 68
 #DEFINE xlPinYin 1
 #DEFINE xlPivotCellBlankCell 9
 #DEFINE xlPivotCellCustomSubtotal 7
 #DEFINE xlPivotCellDataField 4
 #DEFINE xlPivotCellDataPivotField 8
 #DEFINE xlPivotCellGrandTotal 3
 #DEFINE xlPivotCellPageFieldItem 6
 #DEFINE xlPivotCellPivotField 5
 #DEFINE xlPivotCellPivotItem 1
 #DEFINE xlPivotCellSubtotal 2
 #DEFINE xlPivotCellValue 0
 #DEFINE xlPivotChartDropZone 32
 #DEFINE xlPivotChartFieldButton 31
 #DEFINE xlPivotTable -4148
 #DEFINE xlPivotTableReport 1
 #DEFINE xlPivotTableVersion10 1
 #DEFINE xlPivotTableVersion2000 0
 #DEFINE xlPivotTableVersionCurrent -1
 #DEFINE xlPlaceholders 2
 #DEFINE xlPlotArea 19
 #DEFINE xlPLT 12
 #DEFINE xlPlus 9
 #DEFINE xlPlusValues 2
 #DEFINE xlPolynomial 3
 #DEFINE xlPortrait 1
 #DEFINE xlPower 4
 #DEFINE xlPowerTalk 2
 #DEFINE xlPrevious 2
 #DEFINE xlPrimary 1
 #DEFINE xlPrimaryButton 1
 #DEFINE xlPrinter 2
 #DEFINE xlPrintErrorsBlank 1
 #DEFINE xlPrintErrorsDash 2
 #DEFINE xlPrintErrorsDisplayed 0
 #DEFINE xlPrintErrorsNA 3
 #DEFINE xlPrintInPlace 16
 #DEFINE xlPrintNoComments -4142
 #DEFINE xlPrintSheetEnd 1
 #DEFINE xlPriorityHigh -4127
 #DEFINE xlPriorityLow -4134
 #DEFINE xlPriorityNormal -4143
 #DEFINE xlProduct -4149
 #DEFINE xlPrompt 0
 #DEFINE xlPTClassic 20
 #DEFINE xlPTNone 21
 #DEFINE xlPublisher 1
 #DEFINE xlPublishers 5
 #DEFINE xlPyramidBarClustered 109
 #DEFINE xlPyramidBarStacked 110
 #DEFINE xlPyramidBarStacked100 111
 #DEFINE xlPyramidCol 112
 #DEFINE xlPyramidColClustered 106
 #DEFINE xlPyramidColStacked 107
 #DEFINE xlPyramidColStacked100 108
 #DEFINE xlPyramidToMax 2
 #DEFINE xlPyramidToPoint 1
 #DEFINE xlQueryTable 0
 #DEFINE xlR1C1 -4150
 #DEFINE xlRadar -4151
 #DEFINE xlRadarAxisLabels 27
 #DEFINE xlRadarFilled 82
 #DEFINE xlRadarMarkers 81
 #DEFINE xlRange 2
 #DEFINE xlRangeAutoFormat3DEffects1 13
 #DEFINE xlRangeAutoFormat3DEffects2 14
 #DEFINE xlRangeAutoFormatAccounting1 4
 #DEFINE xlRangeAutoFormatAccounting2 5
 #DEFINE xlRangeAutoFormatAccounting3 6
 #DEFINE xlRangeAutoFormatAccounting4 17
 #DEFINE xlRangeAutoFormatClassic1 1
 #DEFINE xlRangeAutoFormatClassic2 2
 #DEFINE xlRangeAutoFormatClassic3 3
 #DEFINE xlRangeAutoFormatClassicPivotTable 31
 #DEFINE xlRangeAutoFormatColor1 7
 #DEFINE xlRangeAutoFormatColor2 8
 #DEFINE xlRangeAutoFormatColor3 9
 #DEFINE xlRangeAutoFormatList1 10
 #DEFINE xlRangeAutoFormatList2 11
 #DEFINE xlRangeAutoFormatList3 12
 #DEFINE xlRangeAutoFormatLocalFormat1 15
 #DEFINE xlRangeAutoFormatLocalFormat2 16
 #DEFINE xlRangeAutoFormatLocalFormat3 19
 #DEFINE xlRangeAutoFormatLocalFormat4 20
 #DEFINE xlRangeAutoFormatNone -4142
 #DEFINE xlRangeAutoFormatPTNone 42
 #DEFINE xlRangeAutoFormatReport1 21
 #DEFINE xlRangeAutoFormatReport10 30
 #DEFINE xlRangeAutoFormatReport2 22
 #DEFINE xlRangeAutoFormatReport3 23
 #DEFINE xlRangeAutoFormatReport4 24
 #DEFINE xlRangeAutoFormatReport5 25
 #DEFINE xlRangeAutoFormatReport6 26
 #DEFINE xlRangeAutoFormatReport7 27
 #DEFINE xlRangeAutoFormatReport8 28
 #DEFINE xlRangeAutoFormatReport9 29
 #DEFINE xlRangeAutoFormatSimple -4154
 #DEFINE xlRangeAutoFormatTable1 32
 #DEFINE xlRangeAutoFormatTable10 41
 #DEFINE xlRangeAutoFormatTable2 33
 #DEFINE xlRangeAutoFormatTable3 34
 #DEFINE xlRangeAutoFormatTable4 35
 #DEFINE xlRangeAutoFormatTable5 36
 #DEFINE xlRangeAutoFormatTable6 37
 #DEFINE xlRangeAutoFormatTable7 38
 #DEFINE xlRangeAutoFormatTable8 39
 #DEFINE xlRangeAutoFormatTable9 40
 #DEFINE xlRangeValueDefault 10
 #DEFINE xlRangeValueMSPersistXML 12
 #DEFINE xlRangeValueXMLSpreadsheet 11
 #DEFINE xlReadOnly 3
 #DEFINE xlReadWrite 2
 #DEFINE xlReference 4
 #DEFINE xlRelative 4
 #DEFINE xlRelRowAbsColumn 3
 #DEFINE xlRepairFile 1
 #DEFINE xlReport1 0
 #DEFINE xlReport10 9
 #DEFINE xlReport2 1
 #DEFINE xlReport3 2
 #DEFINE xlReport4 3
 #DEFINE xlReport5 4
 #DEFINE xlReport6 5
 #DEFINE xlReport7 6
 #DEFINE xlReport8 7
 #DEFINE xlReport9 8
 #DEFINE xlRight -4152
 #DEFINE xlRightBrace 13
 #DEFINE xlRightBracket 11
 #DEFINE xlRoutingComplete 2
 #DEFINE xlRoutingInProgress 1
 #DEFINE xlRowField 1
 #DEFINE xlRowHeader -4153
 #DEFINE xlRowItem 4
 #DEFINE xlRowLabels 1
 #DEFINE xlRows 1
 #DEFINE xlRowSeparator 15
 #DEFINE xlRowThenColumn 1
 #DEFINE xlRTF 4
 #DEFINE xlRTL -5004
 #DEFINE xlRunningTotal 5
 #DEFINE xlSaveChanges 1
 #DEFINE xlScale 3
 #DEFINE xlScaleLinear -4132
 #DEFINE xlScaleLogarithmic -4133
 #DEFINE xlScenario 4
 #DEFINE xlScreen 1
 #DEFINE xlScreenSize 1
 #DEFINE xlScrollBar 8
 #DEFINE xlSecondary 2
 #DEFINE xlSecondaryButton 2
 #DEFINE xlSecondCode 24
 #DEFINE xlSelect 3
 #DEFINE xlSemiautomatic 2
 #DEFINE xlSemiGray75 10
 #DEFINE xlSendPublisher 2
 #DEFINE xlSeries 3
 #DEFINE xlSeriesAxis 3
 #DEFINE xlSeriesLines 22
 #DEFINE xlSet 3
 #DEFINE xlShape 14
 #DEFINE xlShared 2
 #DEFINE xlSheetHidden 0
 #DEFINE xlSheetVeryHidden 2
 #DEFINE xlSheetVisible -1
 #DEFINE xlShiftDown -4121
 #DEFINE xlShiftToLeft -4159
 #DEFINE xlShiftToRight -4161
 #DEFINE xlShiftUp -4162
 #DEFINE xlShort 1
 #DEFINE xlShowLabel 4
 #DEFINE xlShowLabelAndPercent 5
 #DEFINE xlShowPercent 3
 #DEFINE xlShowValue 2
 #DEFINE xlSides 1
 #DEFINE xlSimple -4154
 #DEFINE xlSinceMyLastSave 1
 #DEFINE xlSingle 2
 #DEFINE xlSingleAccounting 4
 #DEFINE xlSingleQuote 2
 #DEFINE xlSizeIsArea 1
 #DEFINE xlSizeIsWidth 2
 #DEFINE xlSkipColumn 9
 #DEFINE xlSlantDashDot 13
 #DEFINE xlSmartTagControlActiveX 13
 #DEFINE xlSmartTagControlButton 6
 #DEFINE xlSmartTagControlCheckbox 9
 #DEFINE xlSmartTagControlCombo 12
 #DEFINE xlSmartTagControlHelp 3
 #DEFINE xlSmartTagControlHelpURL 4
 #DEFINE xlSmartTagControlImage 8
 #DEFINE xlSmartTagControlLabel 7
 #DEFINE xlSmartTagControlLink 2
 #DEFINE xlSmartTagControlListbox 11
 #DEFINE xlSmartTagControlRadioGroup 14
 #DEFINE xlSmartTagControlSeparator 5
 #DEFINE xlSmartTagControlSmartTag 1
 #DEFINE xlSmartTagControlTextbox 10
 #DEFINE xlSolid 1
 #DEFINE xlSortColumns 1
 #DEFINE xlSortLabels 2
 #DEFINE xlSortNormal 0
 #DEFINE xlSortRows 2
 #DEFINE xlSortTextAsNumbers 1
 #DEFINE xlSortValues 1
 #DEFINE xlSourceAutoFilter 3
 #DEFINE xlSourceChart 5
 #DEFINE xlSourcePivotTable 6
 #DEFINE xlSourcePrintArea 2
 #DEFINE xlSourceQuery 7
 #DEFINE xlSourceRange 4
 #DEFINE xlSourceSheet 1
 #DEFINE xlSourceWorkbook 0
 #DEFINE xlSpeakByColumns 1
 #DEFINE xlSpeakByRows 0
 #DEFINE xlSpecifiedTables 3
 #DEFINE xlSpinner 9
 #DEFINE xlSplitByCustomSplit 4
 #DEFINE xlSplitByPercentValue 3
 #DEFINE xlSplitByPosition 1
 #DEFINE xlSplitByValue 2
 #DEFINE xlSquare 1
 #DEFINE xlSrcExternal 0
 #DEFINE xlSrcRange 1
 #DEFINE xlSrcXml 2
 #DEFINE xlStack 2
 #DEFINE xlStackScale 3
 #DEFINE xlStandardSummary 1
 #DEFINE xlStar 5
 #DEFINE xlStDev -4155
 #DEFINE xlStDevP -4156
 #DEFINE xlStError 4
 #DEFINE xlStockHLC 88
 #DEFINE xlStockOHLC 89
 #DEFINE xlStockVHLC 90
 #DEFINE xlStockVOHLC 91
 #DEFINE xlStretch 1
 #DEFINE xlStrict 2
 #DEFINE xlStroke 2
 #DEFINE xlSubscriber 2
 #DEFINE xlSubscribers 6
 #DEFINE xlSubscribeToPicture -4147
 #DEFINE xlSubscribeToText -4158
 #DEFINE xlSubtract 3
 #DEFINE xlSum -4157
 #DEFINE xlSummaryAbove 0
 #DEFINE xlSummaryBelow 1
 #DEFINE xlSummaryOnLeft -4131
 #DEFINE xlSummaryOnRight -4152
 #DEFINE xlSummaryPivotTable -4148
 #DEFINE xlSurface 83
 #DEFINE xlSurfaceTopView 85
 #DEFINE xlSurfaceTopViewWireframe 86
 #DEFINE xlSurfaceWireframe 84
 #DEFINE xlSYLK 2
 #DEFINE xlSyllabary 1
 #DEFINE xlSystem 1
 #DEFINE xlTable1 10
 #DEFINE xlTable10 19
 #DEFINE xlTable2 11
 #DEFINE xlTable3 12
 #DEFINE xlTable4 13
 #DEFINE xlTable5 14
 #DEFINE xlTable6 15
 #DEFINE xlTable7 16
 #DEFINE xlTable8 17
 #DEFINE xlTable9 18
 #DEFINE xlTableBody 8
 #DEFINE xlTabPositionFirst 0
 #DEFINE xlTabPositionLast 1
 #DEFINE xlTabular 0
 #DEFINE xlTemplate 17
 #DEFINE xlTenMillions -7
 #DEFINE xlTenThousands -4
 #DEFINE xlText -4158
 #DEFINE xlTextBox 16
 #DEFINE xlTextDate 2
 #DEFINE xlTextFormat 2
 #DEFINE xlTextImport 6
 #DEFINE xlTextMac 19
 #DEFINE xlTextMSDOS 21
 #DEFINE xlTextPrinter 36
 #DEFINE xlTextQualifierDoubleQuote 1
 #DEFINE xlTextQualifierNone -4142
 #DEFINE xlTextQualifierSingleQuote 2
 #DEFINE xlTextValues 2
 #DEFINE xlTextVisualLTR 1
 #DEFINE xlTextVisualRTL 2
 #DEFINE xlTextWindows 20
 #DEFINE xlThick 4
 #DEFINE xlThin 2
 #DEFINE xlThousandMillions -9
 #DEFINE xlThousands -3
 #DEFINE xlThousandsSeparator 4
 #DEFINE xlTickLabelOrientationAutomatic -4105
 #DEFINE xlTickLabelOrientationDownward -4170
 #DEFINE xlTickLabelOrientationHorizontal -4128
 #DEFINE xlTickLabelOrientationUpward -4171
 #DEFINE xlTickLabelOrientationVertical -4166
 #DEFINE xlTickLabelPositionHigh -4127
 #DEFINE xlTickLabelPositionLow -4134
 #DEFINE xlTickLabelPositionNextToAxis 4
 #DEFINE xlTickLabelPositionNone -4142
 #DEFINE xlTickMarkCross 4
 #DEFINE xlTickMarkInside 2
 #DEFINE xlTickMarkNone -4142
 #DEFINE xlTickMarkOutside 3
 #DEFINE xlTIF 9
 #DEFINE xlTiled 1
 #DEFINE xlTimeLeadingZero 45
 #DEFINE xlTimeScale 3
 #DEFINE xlTimeSeparator 18
 #DEFINE xlTitleBar 8
 #DEFINE xlToLeft -4159
 #DEFINE xlToolbar 1
 #DEFINE xlToolbarButton 2
 #DEFINE xlToolbarProtectionNone -4143
 #DEFINE xlTop -4160
 #DEFINE xlTop10Items 3
 #DEFINE xlTop10Percent 5
 #DEFINE xlTopToBottom 1
 #DEFINE xlToRight -4161
 #DEFINE xlTotalsCalculationAverage 2
 #DEFINE xlTotalsCalculationCount 3
 #DEFINE xlTotalsCalculationCountNums 4
 #DEFINE xlTotalsCalculationMax 6
 #DEFINE xlTotalsCalculationMin 5
 #DEFINE xlTotalsCalculationNone 0
 #DEFINE xlTotalsCalculationStdDev 7
 #DEFINE xlTotalsCalculationSum 1
 #DEFINE xlTotalsCalculationVar 8
 #DEFINE xlTransparent 2
 #DEFINE xlTrendline 8
 #DEFINE xlTriangle 3
 #DEFINE xlUnderlineStyleDouble -4119
 #DEFINE xlUnderlineStyleDoubleAccounting 5
 #DEFINE xlUnderlineStyleNone -4142
 #DEFINE xlUnderlineStyleSingle 2
 #DEFINE xlUnderlineStyleSingleAccounting 4
 #DEFINE xlUnicodeText 42
 #DEFINE xlUnknown 1000
 #DEFINE xlUnlockedCells 1
 #DEFINE xlUnlockedFormulaCells 6
 #DEFINE xlUp -4162
 #DEFINE xlUpBars 18
 #DEFINE xlUpdateLinksAlways 3
 #DEFINE xlUpdateLinksNever 2
 #DEFINE xlUpdateLinksUserSetting 1
 #DEFINE xlUpdateState 1
 #DEFINE xlUpdateSubscriber 2
 #DEFINE xlUpperCaseColumnLetter 7
 #DEFINE xlUpperCaseRowLetter 6
 #DEFINE xlUpward -4171
 #DEFINE xlUserDefined 22
 #DEFINE xlUserResolution 1
 #DEFINE xlValidAlertInformation 3
 #DEFINE xlValidAlertStop 1
 #DEFINE xlValidAlertWarning 2
 #DEFINE xlValidateCustom 7
 #DEFINE xlValidateDate 4
 #DEFINE xlValidateDecimal 2
 #DEFINE xlValidateInputOnly 0
 #DEFINE xlValidateList 3
 #DEFINE xlValidateTextLength 6
 #DEFINE xlValidateTime 5
 #DEFINE xlValidateWholeNumber 1
 #DEFINE xlVAlignBottom -4107
 #DEFINE xlVAlignCenter -4108
 #DEFINE xlVAlignDistributed -4117
 #DEFINE xlVAlignJustify -4130
 #DEFINE xlVAlignTop -4160
 #DEFINE xlVALU 8
 #DEFINE xlValue 2
 #DEFINE xlValues -4163
 #DEFINE xlVar -4164
 #DEFINE xlVarP -4165
 #DEFINE xlVerbOpen 2
 #DEFINE xlVerbPrimary 1
 #DEFINE xlVertical -4166
 #DEFINE xlVeryHidden 2
 #DEFINE xlVisible 12
 #DEFINE xlVisualCursor 2
 #DEFINE xlWait 2
 #DEFINE xlWalls 5
 #DEFINE xlWatchPane 11
 #DEFINE xlWBATChart -4109
 #DEFINE xlWBATExcel4IntlMacroSheet 4
 #DEFINE xlWBATExcel4MacroSheet 3
 #DEFINE xlWBATWorksheet -4167
 #DEFINE xlWebArchive 45
 #DEFINE xlWebFormattingAll 1
 #DEFINE xlWebFormattingNone 3
 #DEFINE xlWebFormattingRTF 2
 #DEFINE xlWebQuery 4
 #DEFINE xlWeekday 2
 #DEFINE xlWeekdayNameChars 31
 #DEFINE xlWhole 1
 #DEFINE xlWide 3
 #DEFINE xlWindows 2
 #DEFINE xlWithinSheet 1
 #DEFINE xlWithinWorkbook 2
 #DEFINE xlWJ2WD1 14
 #DEFINE xlWJ3 40
 #DEFINE xlWJ3FJ3 41
 #DEFINE xlWK1 5
 #DEFINE xlWK1ALL 31
 #DEFINE xlWK1FMT 30
 #DEFINE xlWK3 15
 #DEFINE xlWK3FM3 32
 #DEFINE xlWK4 38
 #DEFINE xlWKS 4
 #DEFINE xlWMF 2
 #DEFINE xlWorkbook 1
 #DEFINE xlWorkbookNormal -4143
 #DEFINE xlWorkbookTab 6
 #DEFINE xlWorks2FarEast 28
 #DEFINE xlWorksheet -4167
 #DEFINE xlWorksheet4 1
 #DEFINE xlWorksheetCell 3
 #DEFINE xlWorksheetShort 5
 #DEFINE xlWPG 3
 #DEFINE xlWQ1 34
 #DEFINE xlX -4168
 #DEFINE xlXErrorBars 10
 #DEFINE xlXmlExportSuccess 0
 #DEFINE xlXmlExportValidationFailed 1
 #DEFINE xlXmlImportElementsTruncated 1
 #DEFINE xlXmlImportSuccess 0
 #DEFINE xlXmlImportValidationFailed 2
 #DEFINE xlXmlLoadImportToList 2
 #DEFINE xlXmlLoadMapXml 3
 #DEFINE xlXmlLoadOpenXml 1
 #DEFINE xlXmlLoadPromptUser 0
 #DEFINE xlXMLSpreadsheet 46
 #DEFINE xlXYScatter -4169
 #DEFINE xlXYScatterLines 74
 #DEFINE xlXYScatterLinesNoMarkers 75
 #DEFINE xlXYScatterSmooth 72
 #DEFINE xlXYScatterSmoothNoMarkers 73
 #DEFINE xlY 1
 #DEFINE xlYDMFormat 8
 #DEFINE xlYear 4
 #DEFINE xlYearCode 19
 #DEFINE xlYears 2
 #DEFINE xlYErrorBars 11
 #DEFINE xlYes 1
 #DEFINE xlYMDFormat 5
 #DEFINE xlZero 2
 }


implementation

end.
